export const SEARCH_PODCASTS_START = 'SEARCH_PODCASTS_START';
export const SEARCH_PODCASTS_SUCCESS = 'SEARCH_PODCASTS_SUCCESS';
export const SEARCH_PODCASTS_FAIL = 'SEARCH_PODCASTS_FAIL';

export const GET_FEED_START = 'GET_FEED_START';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export const GET_FEED_FAIL = 'GET_FEED_FAIL';
